server:
  port: 29000

spring:
  application:
    name: newbee-user-service-web

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  datasource:
    url: jdbc:mysql://121.37.71.228:3308/newbee_mall_cloud_user_db?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
