server:
  port: 29030

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_order_db?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: notsosecure
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      # filters: stat,wall,log4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
#      stat-view-servlet:
#        url-pattern: /druid/*
#        # IP 白名单，没有配置或者为空，则允许所有访问
#        allow: 127.0.0.1
#        # IP 黑名单，若白名单也存在，则优先使用
#        deny: 192.168.31.253
#        # 禁用 HTML 中 Reset All 按钮
#        reset-enable: false
#        # 登录用户名/密码
#        login-username: root
#        login-password: 123

  redis:
    database: 13
    host: localhost
    port: 6379
    password: notsosecure
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public

  application:
    name: order-service

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  enabled: true
  application-id: goods-server
  tx-service-group: test_save_order_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      cluster: default
  service:
    vgroup-mapping:
      test_save_order_group: default
  enable-auto-data-source-proxy: true