server:
  port: 29000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_user_db?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: notsosecure
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      # validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 13
    host: localhost
    port: 6379
    password: notsosecure
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public

  application:
    name: user-service

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  enabled: true
  application-id: cart-server
  tx-service-group: test_save_order_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 121.37.71.228:8848
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      cluster: default
  service:
    vgroup-mapping:
      test_save_order_group: default